### ISSUE TITLE
get-misp-iocs.py 'An Internal Error Has Occurred' 

### ISSUE THREAD

**Issue by zachsis** [Neo23x0/signature-base#55]
Error trying to collect misp IOC's from CIRCL using `threatintel/get-misp-iocs.py` 

```
[root@myhost signature-base-master]# python36 threatintel/get-misp-iocs.py 

CRITICAL [api.py:243 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.101 - Python 3.6.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '15', 'Authorization': 'REDACTED', 'content-type': 'application/json'}
Request body:
{"last": "30d"}
Response (if any):
{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/events/restSearch/download'}
Traceback (most recent call last):
  File "threatintel/get-misp-iocs.py", line 195, in <module>
    misp_receiver.get_iocs_last(args.l)
  File "threatintel/get-misp-iocs.py", line 48, in get_iocs_last
    self.events = result['response']
KeyError: 'response'
```

**Comment by zachsis** [comment]
I'm not 100% sure if this is related specifically to CIRCL's misp instance. I will test another tomorrow to validate its not an isolated issue.

**Comment by Neo23x0** [comment]
These scripts are EOL and out of support.
