### ISSUE TITLE
AttributeError: 'PyMISP' object has no attribute 'download_last'

### ISSUE THREAD

**Issue by fl0mb** [Neo23x0/signature-base#90]
Traceback (most recent call last):
  File ".\get-misp-iocs.py", line 195, in <module>
    misp_receiver.get_iocs_last(args.l)
  File ".\get-misp-iocs.py", line 47, in get_iocs_last
    result = self.misp.download_last(last)
AttributeError: 'PyMISP' object has no attribute 'download_last'

**Comment by Neo23x0** [comment]
Tool is obsolete - not supported anymore
